### ISSUE TITLE
Upgrade to newer dependency version for pandas and numpy

### ISSUE THREAD

**Issue by FloBay** [kusterlab/psite_annotation#11]
It would be nice to eventually allow (if no breaks occur) numpy >=2.0, which goes in hand with pandas >=2.2.2. This will keep everything up-to-date and in sync :) 

Currently:
```
numpy = "^1.18.1"
pandas = ">=1.3.0"
```

**Comment by MatthewThe** [comment]
Making this change may require updating tools/packages that depend on psite-annotation. However, I think changing `^1.18.1` to `>=1.18.1,<3.0` would at least allow numpy >= 2.0. I'll test if this works.
