### ISSUE TITLE
Preserve Order within Annotation Columns

### ISSUE THREAD

**Issue by jmueller95** [kusterlab/psite_annotation#14]
The columns added by `addPeptideAndPsitePositions` are ';'-separated lists. But these lists are not in sync right now. To Dos:
1. Do not remove duplicates from the 'Site Sequence Context' Column.
2. Preserve the order across all ';'-separated columns.

**Comment by FloBay** [comment]
can this be an optional parameter to either preserve or not.. For me duplicates are super annoying and sorting them alphabetically is also guaranteeing that always the same string comes back independent of the input. I like this behavior actually a lot .. 

Especially with this example. Why would you want this duplicated information:
![image](https://github.com/user-attachments/assets/06912c72-4c97-4ba9-bc6a-aeed9ce48176)
