### ISSUE TITLE
PSP header contains wiered symbol that causes pandas read_csv error

### ISSUE THREAD

**Issue by FloBay** [kusterlab/psite_annotation#6]
That is the problematic word (D261Ð70). 

This raises a UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 646: invalid continuation byte
at 
```
def load_annotations(self) -> None:
30     """Reads in tab separated file with PhosphositePlus annotations."""
 31     self.psp_df = pd.read_csv(self.annotation_file, sep="\t", skiprows=3)
```

I can get the same pandas UnicodeDecodeError with:
`pd.read_csv(pa.pspKinaseSubstrateFile, sep="\t", skiprows=3)`

When fixing the encoder to utf-8, pandas can read the file again:
`pd.read_csv(pa.pspKinaseSubstrateFile, sep="\t", skiprows=3, encoding='utf-8')`

No clue why, but it can be an easy fix with low priority...
Here is the newest file to reproduce the error... 
[Kinase_Substrate_Dataset.txt](https://github.com/kusterlab/psite_annotation/files/13939063/Kinase_Substrate_Dataset.txt)
Of course, one can ask people to change the header manually, but that is not so convenient.

**Comment by MatthewThe** [comment]
Thanks, should be fixed in `develop` now!
