### ISSUE TITLE
Allow users to set the which amino acid is expected to carry a PTM when localization uncertainty is enabled

### ISSUE THREAD

**Issue by FloBay** [kusterlab/psite_annotation#7]
https://github.com/kusterlab/psite_annotation/blob/bcc8f069930aa841301ca30d8bc3bd538769f55a/psite_annotation/annotators/peptide_position.py#L284

In the annotator, Lys is currently considered to be an unlocalized position that can carry a phosphorylation, which obviously makes no sense. Make this an optional user parameter so that one can specify how many positions to consider and which aa can be an acceptor site. 
```python
sty = ['S', 'T', 'Y']
phosphosites_df = pa.addPeptideAndPsitePositions(df, pa.pspFastaFile, pspInput=True, localization_uncertainty=2, mod_acceptors=sty)
```

This could also be more advanced in that one provides a dictionary that specifies the different mods and the possibilities. e.g.
```python
accpetor_mods = {'(ph)': ['S', 'T', 'Y'], '(ac)': ['K'], '(me)': ['K', 'R']...}

**Comment by MatthewThe** [comment]
Completely agree that this should be possible.

The simple solution should be relatively easy to implement.

The more advanced option will require some code restructuring, because we already discarded the information about the type of modification in the lines of code you refer to.
